# Generated by Django 6.0.3 on 2026-03-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='tipo',
            field=models.CharField(choices=[('aviso', 'Aviso'), ('asignacion', 'Asignacion')], default='aviso', max_length=20),
        ),
    ]
