# Generated by Django 6.0.3 on 2026-03-18 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avisos", "0002_aviso_tipo"),
        ("usuarios", "0002_remove_usuario_cargo_usuario_rol_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aviso",
            name="directiva",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avisos_directiva",
                to="usuarios.usuario",
            ),
        ),
    ]
