# Generated by Django 6.0.3 on 2026-03-17 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='chat/archivos/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('es_sistema', models.BooleanField(default=False)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='departamentos.departamento')),
            ],
            options={
                'verbose_name': 'mensaje',
                'verbose_name_plural': 'mensajes',
                'ordering': ['fecha'],
            },
        ),
    ]
