# Generated by Django 6.0.3 on 2026-03-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_departamentolectura"),
    ]

    operations = [
        migrations.AddField(
            model_name="departamentolectura",
            name="ultimo_asignacion_id",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="departamentolectura",
            name="ultimo_aviso_id",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
