# Generated by Django 6.0.3 on 2026-03-18 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_departamentolectura_avisos_asignaciones"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MensajeEliminadoUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eliminado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "mensaje",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eliminaciones",
                        to="chat.mensaje",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes_eliminados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "mensaje eliminado para usuario",
                "verbose_name_plural": "mensajes eliminados para usuario",
                "unique_together": {("mensaje", "usuario")},
            },
        ),
    ]
