# Generated by Django 6.0.3 on 2026-03-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cargo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('directiva', 'Directiva'), ('departamento', 'Departamentos')], default='departamento', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_directiva',
            field=models.CharField(blank=True, choices=[('general', 'Director General'), ('administrativo', 'Director Administrativo'), ('tecnologico', 'Director Tecnologico')], max_length=20),
        ),
    ]
