# Generated by GitHub Copilot on 2026-03-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def asignar_directiva_departamentos(apps, schema_editor):
    Departamento = apps.get_model("departamentos", "Departamento")
    Mensaje = apps.get_model("chat", "Mensaje")
    Aviso = apps.get_model("avisos", "Aviso")
    Usuario = apps.get_model("usuarios", "Usuario")

    directivas = list(
        Usuario.objects.filter(rol="directiva").order_by("id").values_list("id", flat=True)
    )
    directiva_unica = directivas[0] if len(directivas) == 1 else None

    for departamento in Departamento.objects.all():
        directiva_id = (
            Mensaje.objects.filter(departamento_id=departamento.id, directiva__isnull=False)
            .order_by("-id")
            .values_list("directiva_id", flat=True)
            .first()
        )
        if not directiva_id:
            directiva_id = (
                Aviso.objects.filter(departamento_id=departamento.id, directiva__isnull=False)
                .order_by("-id")
                .values_list("directiva_id", flat=True)
                .first()
            )
        if not directiva_id and directiva_unica:
            directiva_id = directiva_unica
        if directiva_id:
            departamento.directiva_id = directiva_id
            departamento.save(update_fields=["directiva"])


class Migration(migrations.Migration):

    dependencies = [
        ("departamentos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0006_mensaje_directiva"),
        ("avisos", "0003_aviso_directiva"),
    ]

    operations = [
        migrations.AddField(
            model_name="departamento",
            name="directiva",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departamentos_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(asignar_directiva_departamentos, migrations.RunPython.noop),
    ]
